---
# This automation notifies through Discord if there is a delay at a tracked
# airport. It also notifies if there was a ground stop or closure that has
# since been canceled.

- alias: FAA Notification
  id: "faa_notification"
  mode: queued
  trigger:
    platform: state
    entity_id:
      - binary_sensor.atl_departure_delay
      - binary_sensor.atl_arrival_delay
      - binary_sensor.atl_ground_delay
      - binary_sensor.atl_ground_stop
      - binary_sensor.atl_closed
      - binary_sensor.dtw_departure_delay
      - binary_sensor.dtw_arrival_delay
      - binary_sensor.dtw_ground_delay
      - binary_sensor.dtw_ground_stop
      - binary_sensor.dtw_closed
      - binary_sensor.jfk_departure_delay
      - binary_sensor.jfk_arrival_delay
      - binary_sensor.jfk_ground_delay
      - binary_sensor.jfk_ground_stop
      - binary_sensor.jfk_closed
      - binary_sensor.lga_departure_delay
      - binary_sensor.lga_arrival_delay
      - binary_sensor.lga_ground_delay
      - binary_sensor.lga_ground_stop
      - binary_sensor.lga_closed
      - binary_sensor.bos_departure_delay
      - binary_sensor.bos_arrival_delay
      - binary_sensor.bos_ground_delay
      - binary_sensor.bos_ground_stop
      - binary_sensor.bos_closed
      - binary_sensor.ord_departure_delay
      - binary_sensor.ord_arrival_delay
      - binary_sensor.ord_ground_delay
      - binary_sensor.ord_ground_stop
      - binary_sensor.ord_closed
    from: "off"
    to: "on"
  condition:
    condition: state
    entity_id: input_boolean.dumb_mode
    state: "off"
  action:
    service: notify.discord_webhook
    data:
      message: >
        {{ trigger.to_state.name }}
        Reason: {{ trigger.to_state.attributes.reason }}
        {% if trigger.to_state.attributes.end %}
        End: {{ trigger.to_state.attributes.end }}
        {% endif %}

- alias: FAA Notification Cancel
  id: "faa_notification_cancel"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.atl_ground_stop
      - binary_sensor.atl_closed
      - binary_sensor.jfk_ground_stop
      - binary_sensor.jfk_closed
      - binary_sensor.lga_ground_stop
      - binary_sensor.lga_closed
      - binary_sensor.bos_ground_stop
      - binary_sensor.bos_closed
      - binary_sensor.ord_ground_stop
      - binary_sensor.ord_closed
    from: "on"
    to: "off"
  condition:
    condition: state
    entity_id: input_boolean.dumb_mode
    state: "off"
  action:
    service: notify.discord_webhook
    data:
      message: >
        {{ trigger.to_state.name }} Canceled
