---
# This automation alerts us if the smoke detectors go off via a Z-Wave
# Firefighter unit. It also turns on all lights and the air conditioner.

- alias: Fire Alarm
  id: "fire_alarm"
  trigger:
    platform: state
    entity_id: binary_sensor.fire_alarm_sounding
    to: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.all
    - service: notify.all_mobile_apps
      data:
        title: "Fire Alarm Sounding"
        message: "The fire alarm at home is sounding."
        data:
          push:
            interruption-level: critical

- alias: Fire Alarm Cleared
  id: "fire_alarm_cleared"
  trigger:
    platform: state
    entity_id: binary_sensor.smoke_detector_smoke_detected
    from: "on"
    to: "off"
  action:
    - service: notify.all_mobile_apps
      data:
        title: "Fire Alarm Clear"
        message: "The fire alarm is all clear."
        data:
          push:
            interruption-level: time-sensitive
