- alias: Front Door
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    to: 'on'
  condition:
    condition: state
    entity_id: 'person.nathan'
    state: 'not_home'
  action:
    - service: notify.mobile_app_nathans_iphone
      data:
        title: "Front Door"
        message: "The front door is open!"
        data:
          attachment:
            content-type: jpeg
          push:
            category: camera
          entity_id: camera.amcrest_camera
    - service: homeassistant.turn_on
      data:
        entity_id: group.all_lights
#This is depreciated, need to fix
#    - service: script.marantz_speak
#      data:
#        mp3filename: "alarm"
#        loop: "yes"
