---
# This automation notifies us if the front door is opened while no one is home.
# The notification includes a stream from the camera which is pointed at the
# front door.

- alias: Front Door
  id: "front_door"
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    to: "on"
  condition:
    - condition: state
      entity_id: "group.home_devices"
      state: "not_home"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: "off"
  action:
    - service: notify.all_mobile_apps
      data:
        title: "Front Door"
        message: "The front door is open!"
    - service: light.turn_on
      data:
        entity_id: light.all

- alias: Front Door Guest
  id: "front_door_guest"
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    to: "on"
  condition:
    - condition: state
      entity_id: "group.home_devices"
      state: "not_home"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "on"
  action:
    - service: notify.all_mobile_apps
      data:
        title: "Front Door"
        message: "Cat sitter is here!"
    - service: scene.turn_on
      data:
        entity_id: scene.normal_lights
