---
# This automation sends a notification if someone attempts to login and is not
# successful.

- alias: Notify of Failed Login Attempt
  id: "notify_of_failed_login_attempt"
  trigger:
    - platform: state
      entity_id: persistent_notification.http_login
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state != off }}"
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: "off"
  action:
    - service: notify.mobile_app_nathans_iphone
      data:
        title: "Failed Home Assistant login attempt!"
        message: "{{ trigger.to_state.attributes.message }}"
        data:
          url: http://www.ip-tracker.org/locator/ip-lookup.php?ip={{ states.persistent_notification.http_login.attributes.message.split("from ")[1] }}
