---
# This automation sends a notification when updates are available for an add on,
# HA core, HACS component, or HA OS.

- alias: Update Available
  id: "update_available"
  trigger:
    - platform: time
      at: "09:30:00"
  condition:
    - alias: "Updates are available"
      condition: state
      entity_id: group.updaters
      state: "on"
  action:
    service: notify.mobile_app_nathans_iphone
    data:
      title: "Update(s) available"
      message: >
        {% for entity in expand('group.updaters') %}
        {% if entity.state == 'on' %}
        Update available for {{ entity.attributes.friendly_name }}
        {% endif %}
        {% endfor %}
      data:
        push:
          interruption-level: passive
