---
#This sets up the Dark Sky weather integration.
#https://www.home-assistant.io/components/darksky/

#This is the weather integration used to display in the frontend.
weather:
  - platform: darksky
    api_key: !secret darksky_api

#This builds the sensors that are processed for notifications.
sensor:
  - platform: darksky
    api_key: !secret darksky_api
    forecast:
      - 0
    hourly_forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - icon
      - precip_type
      - temperature
      - apparent_temperature
      - dew_point
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_high
      - temperature_low
      - apparent_temperature_high
      - apparent_temperature_low
      - uv_index
      - nearest_storm_distance
    scan_interval:
      minutes: 3
