---

- platform: group
  name: Bathroom Lights
  entities:
    - light.bathroom_light_1
    - light.bathroom_light_2
    - light.bathroom_light_3
- platform: group
  name: all
  entities:
    - light.bedroom_lamp
