---
- platform: template
  sensors:
    precip_type:
      value_template: >
        {% if states("weather.katl_hourly") in ['clear-night', 'cloudy', 'fog', 'partlycloudy', 'sunny', 'windy', 'windy-variant'] %}
        None
        {% else %}
        {{ states("weather.katl_hourly") }}
        {% endif %}
    next_report_time:
      value_template: >
        {{ strptime(state_attr('calendar.work', 'description').split('\n')[0] | replace('Report: ', '') | replace('L', '') + state_attr('calendar.work', 'start_time').split(' ')[0], '%H%M%Y-%m-%d') }}
      availability_template: >
        {{ 'Report' in state_attr('calendar.work', 'description') }}
    nws_temperature:
      friendly_name: NWS Temperature
      value_template: '{{ state_attr("weather.katl_hourly", "temperature") }}'
      unit_of_measurement: "°F"
    last_litter_box:
      friendly_name: Last Cleaning
      value_template: '{{ states.input_datetime.last_litter_box.attributes.timestamp | timestamp_custom("%Y-%m-%dT%H:%M:%S%z") }}'
      device_class: timestamp
    next_litter_box:
      friendly_name: Next Cleaning
      value_template: '{{ (state_attr("input_datetime.last_litter_box", "timestamp") + 172800) | timestamp_custom("%Y-%m-%dT%H:%M:%S%z") }}'
      attribute_templates:
        timestamp: '{{ (state_attr("input_datetime.last_litter_box", "timestamp") + 172800) }}'
      device_class: timestamp
    last_vacuum:
      friendly_name: Last Vacuum Run
      value_template: "{{ states.vacuum.rockrobo.last_changed.isoformat() }}"
      device_class: timestamp
    next_vacuum:
      friendly_name: Next Vacuum
      value_template: '{{ (states("sensor.last_vacuum") | as_timestamp() + 259200) | timestamp_custom("%Y-%m-%dT%H:%M:%S%z") }}'
      device_class: timestamp
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "time_date"
    - "date_time_iso"
    - "time_utc"
- platform: statistics
  name: Outdoor Temperature Stats
  entity_id: sensor.outdoor_temperature
  sampling_size: 500
  max_age:
    hours: 24
- platform: weatheralerts
  state: WA
  county: 53
  zone: 509
- platform: rest
  resource: https://www.aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=xml&hoursBeforeNow=3&mostRecent=true&stationString=KATL
  name: ATL METAR
  value_template: "{{ value_json.response.data.METAR.flight_category }}"
  json_attributes_path: "{{ value_json.response.data.METAR }}"
- platform: systemmonitor
  resources:
    - type: disk_use_percent
    - type: memory_use_percent
    - type: load_15m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: ipv4_address
      arg: eth0
    - type: ipv6_address
      arg: eth0
    - type: processor_use
    - type: processor_temperature
    - type: last_boot
- platform: min_max
  entity_ids:
    - sensor.bathroom_temperature
    - sensor.bathroom_temperature_z
    - sensor.bedroom_temperature_z
    - sensor.kitchen_temperature_z
    - sensor.living_room_temperature
  type: mean
  name: Indoor Temperature
- platform: filter
  name: PM1
  entity_id: sensor.particulate_matter_1_0um_concentration
  filters:
    - filter: time_simple_moving_average
      window_size: "00:02"
      precision: 2
- platform: filter
  name: PM2.5
  entity_id: sensor.particulate_matter_2_5um_concentration
  filters:
    - filter: time_simple_moving_average
      window_size: "00:02"
      precision: 2
- platform: filter
  name: PM10
  entity_id: sensor.particulate_matter_10_0um_concentration
  filters:
    - filter: time_simple_moving_average
      window_size: "00:05"
      precision: 1
