---

- platform: template
  sensors:
    hvac_action:
      friendly_name: HVAC Action
      value_template: '{{ state_attr("climate.thermostat", "hvac_action") }}'
    indoor_temperature:
      friendly_name: Indoor Temperature
      value_template: '{{ ((float(states.sensor.bathroom_temperature.state) + float(states.sensor.thermostat_temperature.state) + float(states.sensor.bathroom_temperature_z.state) + float(states.sensor.bedroom_temperature_z.state) + float(states.sensor.bedroom_temperature.state) + float(states.sensor.hallway_temperature_z.state) + float(states.sensor.living_room_temperature_z.state)) / 7) | round(1) }}'
      unit_of_measurement: '°F'
    precip_type:
      value_template: >
        {% if states("weather.katl") in ['clear-night', 'cloudy', 'fog', 'partlycloudy', 'sunny', 'windy', 'windy-variant'] %}
        None
        {% else %}
        {{ states("weather.katl") }}
        {% endif %}
    outdoor_temperature:
      friendly_name: Outdoor Temperature
      value_template: '{{ state_attr("weather.katl", "temperature") }}'
      unit_of_measurement: '°F'
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_date'
    - 'time_utc'
- platform: history_stats
  name: AC Cool Today
  entity_id: sensor.hvac_action
  state: 'cooling'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: AC Heat Today
  entity_id: sensor.hvac_action
  state: 'heating'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: scrape
  name: NPR News Scrape
  resource: https://www.npr.org/rss/podcast.php?id=500005
  select: 'enclosure'
  attribute: 'url'
- platform: statistics
  name: Outdoor Temperature Stats
  entity_id: sensor.outdoor_temperature
  sampling_size: 500
  max_age:
    hours: 24
- platform: xfinity
  username: !secret xfinity_user
  password: !secret xfinity_pass
- platform: weatheralerts
  state: GA
  county: 121
  zone: 33
- platform: waze_travel_time
  origin: zone.home
  destination: zone.atl
  region: 'US'
  name: Travel Home to ATL
- platform: waze_travel_time
  origin: zone.atl
  destination: zone.home
  region: 'US'
  name: Travel ATL to Home
- platform: waze_travel_time
  origin: zone.home
  destination: zone.gdot
  region: 'US'
  name: Travel Home to GDOT
- platform: waze_travel_time
  origin: zone.gdot
  destination: zone.home
  region: 'US'
  name: Travel GDOT to Home
- platform: faastatus
  id: ATL
- platform: faastatus
  id: DTW
- platform: faastatus
  id: LGA
- platform: faastatus
  id: JFK
- platform: faastatus
  id: BOS
- platform: faastatus
  id: ORD
- platform: rest
  resource: https://www.aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=xml&hoursBeforeNow=3&mostRecent=true&stationString=KATL
  name: ATL METAR
  value_template: '{{ value_json.response.data.METAR.flight_category }}'
  json_attributes_path: '{{ value_json.response.data.METAR }}'
