- platform: template
  sensors:
    hvac_action:
      friendly_name: HVAC Action
      value_template: '{{ state_attr("climate.ct_100", "hvac_action") }}'
    indoor_temperature:
      friendly_name: Indoor Temperature
      value_template: '{{ ((float(states.sensor.bathroom_temperature.state) + float(states.sensor.ct_100_temperature.state) + float(states.sensor.bathroom_temperature_z.state) + float(states.sensor.bedroom_temperature_z.state) + float(states.sensor.hallway_temperature_z.state) + float(states.sensor.living_room_temperature_z.state)) / 6) | round(1) }}'
      unit_of_measurement: '°F'
- platform: mqtt
  name: "ATL End Time"
  state_topic: "delays/ATL"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "DTW End Time"
  state_topic: "delays/DTW"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "LGA End Time"
  state_topic: "delays/LGA"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "JFK End Time"
  state_topic: "delays/JFK"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "BOS End Time"
  state_topic: "delays/BOS"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "ORD End Time"
  state_topic: "delays/ORD"
  value_template: "{{ value_json.EndTime }}"
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_date'
    - 'time_utc'
- platform: history_stats
  name: AC Cool Today
  entity_id: sensor.hvac_action
  state: 'cooling'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: AC Heat Today
  entity_id: sensor.hvac_action
  state: 'heating'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: darksky
  api_key: !secret darksky_api
  forecast:
    - 0
  hourly_forecast:
    - 0
    - 1
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - temperature
    - apparent_temperature
    - dew_point
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
    - uv_index
    - nearest_storm_distance
  scan_interval:
    minutes: 3
- platform: scrape
  name: NPR News Scrape
  resource: https://www.npr.org/rss/podcast.php?id=500005
  select: 'enclosure'
  attribute: 'url'
- platform: statistics
  name: Outdoor Temperature Stats
  entity_id: sensor.dark_sky_temperature
  sampling_size: 500
  max_age:
    hours: 24
