- platform: template
  sensors:
    hvac_action:
      friendly_name: HVAC Action
      value_template: '{{ state_attr("climate.ct_100_cool", "hvac_action") }}'
    indoor_temperature:
      friendly_name: Indoor Temperature
      value_template: '{{ ((float(states.sensor.bedroom_temperature.state) + float(states.sensor.bathroom_temperature.state) + float(states.sensor.ct_100_temperature.state)) / 3) | round(1) }}'
      unit_of_measurement: '°F'
- platform: mqtt
  name: "ATL End Time"
  state_topic: "delays/ATL"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "DTW End Time"
  state_topic: "delays/DTW"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "LGA End Time"
  state_topic: "delays/LGA"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "JFK End Time"
  state_topic: "delays/JFK"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "BOS End Time"
  state_topic: "delays/BOS"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "ORD End Time"
  state_topic: "delays/ORD"
  value_template: "{{ value_json.EndTime }}"
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_date'
    - 'time_utc'
- platform: history_stats
  name: AC Cool Today
  entity_id: sensor.hvac_action
  state: 'cooling'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
- platform: scrape
  name: NPR News Scrape
  resource: https://www.npr.org/rss/podcast.php?id=500005
  select: 'enclosure'
  attribute: 'url'
