---
title: Home
views:
  - path: default_view
    title: Home
    cards:
      #      - type: conditional
      #        conditions:
      #          - entity: sensor.fulton_county
      #            state_not: '0'
      #        card:
      #          type: markdown
      #          content: >
      #            ## Active Weather Alerts:
      #
      #            {% for alert in state_attr("sensor.fulton_county", "alerts") %}
      #              {{ alert.event }}
      #            {%- endfor %}
      - type: glance
        entities:
          #          - binary_sensor.weather_alert
          - person.nathan
          - person.sara
          - sensor.indoor_temperature
          - sensor.openweathermap_temperature
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.home_to_sea
                graph: line
                detail: 1
                name: To SEA
              - type: sensor
                entity: sensor.sea_to_home
                graph: line
                detail: 1
                name: From SEA
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.home_to_wdfw
                graph: line
                detail: 1
                name: To WDFW
              - type: sensor
                entity: sensor.wdfw_to_home
                graph: line
                detail: 1
                name: From WDFW
      - type: button
        entity: light.bathroom_lights
      - type: button
        entity: light.bedroom_lamp
      - type: history-graph
        entities:
          - sensor.indoor_temperature
          - sensor.openweathermap_temperature
        title: Status
      - type: gauge
        entity: sensor.airnow_aqi
        name: Air Quality
        min: 0
        max: 301
        severity:
          green: 0
          yellow: 101
          red: 151
      - type: weather-forecast
        entity: weather.openweathermap
      - type: map
        name: Earthquakes
        geo_location_sources:
          - usgs_earthquakes_feed
        entities:
          - zone.home
        title: Nearby Earthquakes Last Week
      - type: history-graph
        entities:
          - sensor.pm1
          - sensor.pm2_5
          - sensor.pm10
          - sensor.bedroom_particulate_matter_2_5um_concentration

  - path: vacuum
    title: Vacuum
    icon: mdi:robot-vacuum
    cards:
      - type: "custom:vacuum-card"
        entity: vacuum.mater
        map: camera.valetudo_map_rendered_map
        stats:
          default:
            - entity_id: sensor.main_brush
              unit: m
              subtitle: Brush
            - attribute: sensor.right_brush
              unit: m
              subtitle: Side
            - attribute: sensor.main_filter
              unit: m
              subtitle: Filter
            - attribute: sensor.sensor_cleaning
              unit: m
              subtitle: Sensor
          cleaning:
            - attribute: cleanTime
              unit: h
              subtitle: Time
            - attribute: cleanArea
              unit: m2
              subtitle: Area
      #        actions:
      #          - name: Clean Bedroom
      #            icon: mdi:bed
      #            service: vacuum.send_command
      #            service_data:
      #              entity_id: vacuum.rockrobo
      #              command: zoned_cleanup
      #              params:
      #                "zone_ids": ["Bedroom"]
      - type: "custom:valetudo-map-card"
        entity: camera.map_data
        vacuum_entity: vacuum.mater
        rotate: 0
        crop:
          top: 0
          bottom: 0
          left: 0
          right: 0
        min_height: 0

  - path: alarm_clock
    title: Alarm Clock
    icon: mdi:alarm
    cards:
      - type: entities
        entities:
          - input_boolean.alarm_clock_enable
          - input_datetime.alarm_clock
        title: Alarm Clock
        show_header_toggle: false
      - type: entities
        entities:
          - input_boolean.alarm_clock_coffee
          - input_boolean.alarm_clock_lights
        show_header_toggle: false

  - path: living_room
    title: Living Room
    badges:
      - sensor.desk_plug_power
      - sensor.desk_plug_energy
      - sensor.entertainment_center_plug_power
      - sensor.entertainment_center_plug_energy
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Kitchen Sensor
            entities:
              - sensor.kitchen_temperature_z
              - sensor.kitchen_humidity_z
              - sensor.kitchen_illuminance_z
              - binary_sensor.kitchen_motion_z
            show_name: false
      - type: glance
        title: Living Room Sensor
        entities:
          - sensor.living_room_temperature
          - sensor.living_room_humidity
          - binary_sensor.living_room_motion
        show_name: false
      - type: button
        entity: light.living_room_lamp

  - path: bedroom
    title: Bedroom
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Bedroom Sensor (Z)
            entities:
              - sensor.bedroom_temperature_z
              - sensor.bedroom_humidity_z
              - sensor.bedroom_illuminance_z
              - binary_sensor.bedroom_motion_z
            show_name: false
          - type: glance
            title: Bedroom Sensor
            entities:
              - sensor.bedroom_temperature
              - sensor.bedroom_humidity
            show_name: false
      - type: entities
        entities:
          - light.bedroom_lamp
          - light.reading_lamp
      - type: history-graph
        entities:
          - sensor.bedroom_senseair_co2_value

  - path: bathroom
    title: Bathroom
    badges:
      - sensor.washer_plug_power
      - sensor.washer_plug_energy
      - binary_sensor.washer_status
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Bathroom Sensor (Z)
            entities:
              - sensor.bathroom_temperature_z
              - sensor.bathroom_humidity_z
              - sensor.bathroom_illuminance_z
              - binary_sensor.bathroom_motion_z
            show_name: false
          - type: glance
            title: Bathroom Sensor
            entities:
              - sensor.bathroom_temperature
              - sensor.bathroom_humidity
              - sensor.bathroom_luminance
              - binary_sensor.bathroom_motion
            show_name: false

  - path: chores
    title: Chores
    icon: mdi:broom
    cards:
      - type: entities
        title: Litter Box
        entities:
          - sensor.last_litter_box
          - sensor.next_litter_box
          - type: button
            name: Done Now
            icon: mdi:check
            tap_action:
              action: call-service
              service: script.litter_box_done
            action_name: Done
      - type: entities
        title: Vacuum
        entities:
          - sensor.last_vacuum
          - sensor.next_vacuum
          - type: button
            name: Run Now
            icon: mdi:check
            tap_action:
              action: call-service
              service: vacuum.start
              service_data:
                entity_id: vacuum.rockrobo
              confirmation:
                text: Is everything off the ground?
            action_name: Start Vacuum

  - path: media-player
    title: Media Player
    icon: mdi:music
    cards:
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.apple_tv
          - type: horizontal-stack
            cards:
              - type: button
                name: Turn On
                icon: mdi:power-standby
                tap_action:
                  action: call-service
                  service: script.apple_tv_on
              - type: button
                name: Turn Off
                icon: mdi:power-off
                tap_action:
                  action: call-service
                  service: script.apple_tv_off
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: button
                name: Up
                icon: mdi:arrow-up
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:
                    entity_id: remote.apple_tv
                    command: "up"
              - type: vertical-stack
                cards:
                  - type: button
                    name: Left
                    icon: mdi:arrow-left
                    tap_action:
                      action: call-service
                      service: remote.send_command
                      service_data:
                        entity_id: remote.apple_tv
                        command: "left"
                  - type: button
                    name: Right
                    icon: mdi:arrow-right
                    tap_action:
                      action: call-service
                      service: remote.send_command
                      service_data:
                        entity_id: remote.apple_tv
                        command: "right"
              - type: button
                name: Down
                icon: mdi:arrow-down
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:
                    entity_id: remote.apple_tv
                    command: "down"
      - type: media-control
        entity: media_player.spotify_nathan
      - type: media-control
        entity: media_player.marantz_sr5012
      - type: media-control
        entity: media_player.bedroom
      - type: button
        entity: script.spotify_contemporary_blend
        tap_action:
          action: call-service
          service: script.spotify_contemporary_blend

  - path: 3d_printer
    title: 3D Printer
    icon: mdi:printer-3d-nozzle
    badges:
      - binary_sensor.octoprint_printing
      - binary_sensor.octoprint_printing_error
      - sensor.octoprint_current_state
      - sensor.3d_printer_temperature
      - sensor.3d_printer_humidity
    cards:
      - type: history-graph
        entities:
          - sensor.octoprint_target_bed_temp
          - sensor.octoprint_actual_bed_temp
        hours_to_show: 2
        title: Bed Temp
      - type: history-graph
        entities:
          - sensor.octoprint_target_tool0_temp
          - sensor.octoprint_actual_tool0_temp
        title: Nozzle Temp
        hours_to_show: 2
      - type: gauge
        entity: sensor.octoprint_job_percentage
      - type: button
        name: OctoPi
        icon: mdi:raspberry-pi
        entity: switch.octopi
        tap_action:
          confirmation: true
          action: call-service
          service: script.toggle_octopi
      - type: entities
        title: Lights
        entities:
          - light.3d_printer_lights

  - path: delays
    title: Delays
    icon: mdi:airplane
    cards:
      - type: entities
        title: ATL Status
        show_header_toggle: false
        entities:
          - binary_sensor.atl_departure_delay
          - binary_sensor.atl_arrival_delay
          - binary_sensor.atl_ground_delay
          - binary_sensor.atl_ground_stop
          - binary_sensor.atl_closure
      - type: entities
        title: DTW Status
        show_header_toggle: false
        entities:
          - binary_sensor.dtw_departure_delay
          - binary_sensor.dtw_arrival_delay
          - binary_sensor.dtw_ground_delay
          - binary_sensor.dtw_ground_stop
          - binary_sensor.dtw_closure
      - type: entities
        title: LGA Status
        show_header_toggle: false
        entities:
          - binary_sensor.lga_departure_delay
          - binary_sensor.lga_arrival_delay
          - binary_sensor.lga_ground_delay
          - binary_sensor.lga_ground_stop
          - binary_sensor.lga_closure
      - type: entities
        title: JFK Status
        show_header_toggle: false
        entities:
          - binary_sensor.jfk_departure_delay
          - binary_sensor.jfk_arrival_delay
          - binary_sensor.jfk_ground_delay
          - binary_sensor.jfk_ground_stop
          - binary_sensor.jfk_closure
      - type: entities
        title: SEA Status
        show_header_toggle: false
        entities:
          - binary_sensor.sea_departure_delay
          - binary_sensor.sea_arrival_delay
          - binary_sensor.sea_ground_delay
          - binary_sensor.sea_ground_stop
          - binary_sensor.sea_closure

  - path: config
    title: config
    icon: mdi:cog
    cards:
      - type: entities
        title: Status
        show_header_toggle: false
        entities:
          - input_boolean.trip_mode
          - input_boolean.sleep_mode
          - input_boolean.dumb_mode
          - light.all
          - group.home_devices
          - group.updaters
          - sensor.cp1500_status
      - type: entities
        title: Pi-Hole.2
        entities:
          - switch.pi_hole2
          - sensor.pi_hole2_ads_blocked_today
          - sensor.pi_hole2_ads_percentage_blocked_today
          - sensor.pi_hole2_dns_queries_cached
          - sensor.pi_hole2_dns_queries_forwarded
          - sensor.pi_hole2_dns_queries_today
          - sensor.pi_hole2_dns_unique_clients
          - sensor.pi_hole2_dns_unique_domains
          - sensor.pi_hole2_domains_blocked
          - sensor.pi_hole2_seen_clients
      - type: entities
        title: Pi-Hole.5
        entities:
          - switch.pi_hole5
          - sensor.pi_hole5_ads_blocked_today
          - sensor.pi_hole5_ads_percentage_blocked_today
          - sensor.pi_hole5_dns_queries_cached
          - sensor.pi_hole5_dns_queries_forwarded
          - sensor.pi_hole5_dns_queries_today
          - sensor.pi_hole5_dns_unique_clients
          - sensor.pi_hole5_dns_unique_domains
          - sensor.pi_hole5_domains_blocked
          - sensor.pi_hole5_seen_clients

      - type: gauge
        name: CPU Usage
        entity: sensor.processor_use
      - type: gauge
        name: Memory Usage
        entity: sensor.memory_use_percent
      - type: gauge
        name: Disk Usage
        entity: sensor.disk_use_percent
      - type: sensor
        name: CPU Temp
        entity: sensor.processor_temperature
      - type: gauge
        name: UPS Battery
        entity: sensor.cp1500_battery_charge
      - type: history-graph
        entities:
          - sensor.cp1500_input_voltage
