title: Home
views:

  - path: default_view
    title: Home
    badges:
      - person.nathan
      - person.sara
      - binary_sensor.front_door
    cards:
      - type: entity-filter
        entities:
          - input_boolean.trip_mode
          - input_boolean.sleep_mode
          - input_boolean.window_open
          - switch.coffee_maker
          - binary_sensor.front_door
          - binary_sensor.updater
        state_filter:
          - "on"
          - "open"
        show_empty: false
      - type: conditional
        conditions:
          - entity: sensor.dark_sky_precip_0h
            state_not: "unknown"
        card:
          type: markdown
          content: |
            ## {{ states('sensor.dark_sky_precip_0h') | capitalize }}

            {{ states('sensor.dark_sky_precip_0h') }} is expected in the next hour.
      - type: history-graph
        entities:
          - sensor.indoor_temperature
          - sensor.dark_sky_temperature
        title: Status
      - type: weather-forecast
        entity: weather.dark_sky
      - type: picture-entity
        entity: camera.amcrest_camera

  - path: living_room
    title: Living Room
    badges:
      - binary_sensor.front_door
      - binary_sensor.amcrest_camera_motion_detected
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Hallway Sensor
            entities:
              - sensor.hallway_temperature_z
              - sensor.hallway_humidity_z
              - sensor.hallway_luminance_z
              - binary_sensor.hallway_motion_z
            show_name: false
          - type: entity-button
            entity: light.hallway_light
            name: Hallway
      - type: vertical-stack
        cards:
          - type: glance
            title: Living Room Sensor
            entities:
              - sensor.living_room_temperature_z
              - sensor.living_room_humidity_z
              - sensor.living_room_luminance_z
              - binary_sensor.living_room_motion_z
            show_name: false
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: light.kitchen_lights
                name: Kitchen
              - type: entity-button
                entity: switch.coffee_maker
                name: Coffee
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.island_dimmer
                name: Island
              - type: entity-button
                entity: fan.living_room
                name: Fan
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.living_room_lamp
                name: Lamp
              - type: light
                entity: light.couch
                name: Couch


  - path: bedroom
    title: Bedroom
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Bedroom Sensor (Z)
            entities:
              - sensor.bedroom_temperature_z
              - sensor.bedroom_humidity_z
              - sensor.bedroom_luminance_z
              - binary_sensor.bedroom_motion_z
            show_name: false
          - type: glance
            title: Bedroom Sensor
            entities:
              - sensor.bedroom_temperature
              - sensor.bedroom_humidity
              - sensor.bedroom_light
              - binary_sensor.bedroom_motion
            show_name: false
      - type: entities
        entities:
          - light.bedroom_light
          - light.bedroom_lamp
          - light.tv_backlight


  - path: bathroom
    title: Bathroom
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Bathroom Sensor (Z)
            entities:
              - sensor.bathroom_temperature_z
              - sensor.bathroom_humidity_z
              - sensor.bathroom_luminance_z
              - binary_sensor.bathroom_motion_z
            show_name: false
          - type: glance
            title: Bathroom Sensor
            entities:
              - sensor.bathroom_temperature
              - sensor.bathroom_humidity
              - sensor.bathroom_light
              - binary_sensor.bathroom_motion
            show_name: false
      - type: entity-button
        entity: light.bathroom_lights


  - path: climate
    title: Climate
    icon: mdi:air-conditioner
    badges:
      - sensor.ct_100_temperature
      - sensor.ct_100_humidity
      - sensor.hvac_action
      - sensor.ac_cool_today
      - sensor.ac_heat_today
    cards:
      - type: thermostat
        entity: climate.ct_100
      - type: entities
        entities:
          - input_select.climate_mode
          - input_number.climate_heat_point
          - input_number.climate_cool_point
          - input_number.climate_heat_default
          - input_number.climate_cool_default
          - input_number.climate_away_offset
          - input_number.climate_trip_offset
          - input_number.climate_sleep_offset


  - path: media-player
    title: Media Player
    icon: mdi:music
    cards:
      - type: media-control
        entity: media_player.spotify
      - type: media-control
        entity: media_player.marantz_sr5012

  - path: delays
    title: Delays
    icon: mdi:airplane
    badges:
      - binary_sensor.delay_program_status
    cards:
      - type: entities
        title: ATL Delays
        entities:
          - binary_sensor.atl_delay
          - binary_sensor.atl_ground_delay
          - binary_sensor.atl_ground_stop
          - sensor.atl_end_time
          - input_boolean.atl_discord_notify
          - input_boolean.atl_ios_notify
        show_header_toggle: false
      - type: entities
        title: DTW Delays
        entities:
          - binary_sensor.dtw_delay
          - binary_sensor.dtw_ground_delay
          - binary_sensor.dtw_ground_stop
          - sensor.dtw_end_time
          - input_boolean.dtw_discord_notify
          - input_boolean.dtw_ios_notify
        show_header_toggle: false
      - type: entities
        title: LGA Delays
        entities:
          - binary_sensor.lga_delay
          - binary_sensor.lga_ground_delay
          - binary_sensor.lga_ground_stop
          - sensor.lga_end_time
          - input_boolean.lga_discord_notify
          - input_boolean.lga_ios_notify
        show_header_toggle: false
      - type: entities
        title: JFK Delays
        entities:
          - binary_sensor.jfk_delay
          - binary_sensor.jfk_ground_delay
          - binary_sensor.jfk_ground_stop
          - sensor.jfk_end_time
          - input_boolean.jfk_discord_notify
          - input_boolean.jfk_ios_notify
        show_header_toggle: false
      - type: entities
        title: BOS Delays
        entities:
          - binary_sensor.bos_delay
          - binary_sensor.bos_ground_delay
          - binary_sensor.bos_ground_stop
          - sensor.bos_end_time
          - input_boolean.bos_discord_notify
          - input_boolean.bos_ios_notify
        show_header_toggle: false
      - type: entities
        title: ORD Delays
        entities:
          - binary_sensor.ord_delay
          - binary_sensor.ord_ground_delay
          - binary_sensor.ord_ground_stop
          - sensor.ord_end_time
          - input_boolean.ord_discord_notify
          - input_boolean.ord_ios_notify
        show_header_toggle: false

  - path: config
    title: config
    icon: mdi:settings
    cards:
      - type: entities
        title: Status
        entities:
          - input_boolean.trip_mode
          - input_boolean.sleep_mode
          - input_boolean.window_open
          - group.all_lights
      - type: entities
        title: Alarm Clock
        entities:
          - input_boolean.alarm_clock_enable
          - input_datetime.alarm_clock
          - input_boolean.alarm_clock_coffee
      - type: entities
        title: Notification Automations
        entities:
          - automation.front_door
          - automation.climate_notifications
      - type: entities
        title: Light Automations
        entities:
          - automation.away_lights
          - automation.home_lights
      - type: entities
        title: Climate Automations
        entities:
          - automation.climate_set_cool
          - automation.climate_set_heat
          - automation.climate_set_home
          - automation.climate_set_away
          - automation.climate_set_trip
          - automation.climate_set_sleep
          - automation.record_ac_cool_time
      - type: entities
        title: Alarm Clock Automations
        entities:
          - automation.alarm_clock
          - automation.snooze_alarm_clock
          - automation.stop_alarm_clock
      - type: entities
        title: Other Automations
        entities:
          - automation.toggle_trip_mode
          - automation.ios_stop_loop_action
          - automation.turn_guest_mode_on
          - automation.turn_guest_mode_off
      - type: entities
        title: PoE
        entities:
          - switch.poe_port_2
          - switch.poe_port_4
          - switch.poe_port_5
          - switch.poe_port_6
          - switch.poe_port_7
          - switch.poe_port_8
