title: Home
views:

  - path: default_view
    title: Home
    badges:
      - person.nathan
      - binary_sensor.front_door
    cards:
      - type: entity-filter
        entities:
          - group.loopable_scripts
        state_filter:
          - "on"
        card:
          type: entity-button
          tap_action:
            action: call-service
            service: script.script_loop_stop
          entity: script.script_loop_stop
          name: Stop Loop
        show_empty: false
      - type: entity-filter
        entities:
          - input_boolean.trip_mode
          - input_boolean.sleep_mode
          - switch.coffee_maker
          - binary_sensor.front_door
        state_filter:
          - "on"
          - "open"
      - type: history-graph
        entities:
          - sensor.indoor_temperature
          - sensor.dark_sky_temperature
        title: Status
      - type: weather-forecast
        entity: weather.home
      - type: picture-entity
        entity: camera.amcrest_camera

  - path: living_room
    title: Living Room
    badges:
      - binary_sensor.front_door
      - binary_sensor.amcrest_camera_motion_detected
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Hallway Sensor
            entities:
              - sensor.hallway_temperature_z
              - sensor.hallway_humidity_z
              - sensor.hallway_luminance_z
              - binary_sensor.hallway_motion_z
            show_name: false
          - type: entity-button
            entity: light.hallway_light
            name: Hallway
      - type: vertical-stack
        cards:
          - type: glance
            title: Living Room Sensor
            entities:
              - sensor.living_room_temperature_z
              - sensor.living_room_humidity_z
              - sensor.living_room_luminance_z
              - binary_sensor.living_room_motion_z
            show_name: false
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: light.kitchen_lights
                name: Kitchen
              - type: entity-button
                entity: switch.coffee_maker
                name: Coffee
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.island_dimmer
                name: Island
              - type: entity-button
                entity: fan.living_room
                name: Fan


  - path: bedroom
    title: Bedroom
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Bedroom Sensor (Z)
            entities:
              - sensor.bedroom_temperature_z
              - sensor.bedroom_humidity_z
              - sensor.bedroom_luminance_z
              - binary_sensor.bedroom_motion_z
            show_name: false
          - type: glance
            title: Bedroom Sensor
            entities:
              - sensor.bedroom_temperature
              - sensor.bedroom_humidity
              - sensor.bedroom_light
              - binary_sensor.bedroom_motion
            show_name: false
      - type: entities
        entities:
          - light.bedroom_light
          - light.bedroom_lamp
          - light.tv_backlight


  - path: bathroom
    title: Bathroom
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Bathroom Sensor (Z)
            entities:
              - sensor.bathroom_temperature_z
              - sensor.bathroom_humidity_z
              - sensor.bathroom_luminance_z
              - binary_sensor.bathroom_motion_z
            show_name: false
          - type: glance
            title: Bathroom Sensor
            entities:
              - sensor.bathroom_temperature
              - sensor.bathroom_humidity
              - sensor.bathroom_light
              - binary_sensor.bathroom_motion
            show_name: false
      - type: entity-button
        entity: light.bathroom_lights


  - path: climate
    title: Climate
    icon: mdi:air-conditioner
    badges:
      - sensor.ct_100_temperature
      - sensor.ct_100_humidity
      - sensor.hvac_action
      - sensor.ac_cool_today
    cards:
      - type: thermostat
        entity: climate.ct_100_heat
      - type: thermostat
        entity: climate.ct_100_cool
      - type: entities
        entities:
          - input_number.climate_heat_point
          - input_number.climate_cool_point
          - input_number.climate_heat_default
          - input_number.climate_cool_default
          - input_number.climate_away_offset
          - input_number.climate_trip_offset
          - input_number.climate_sleep_offset


  - path: media-player
    title: Media Player
    icon: mdi:music
    cards:
      - type: media-control
        entity: media_player.spotify
      - type: media-control
        entity: media_player.marantz_sr5012

  - path: delays
    title: Delays
    icon: mdi:airplane
    badges:
      - binary_sensor.delay_program_status
    cards:
      - type: entities
        title: ATL Delays
        entities:
          - sensor.atl_delay
          - sensor.atl_ground_delay
          - sensor.atl_ground_stop
          - sensor.atl_end_time
          - input_boolean.atl_notify
        show_header_toggle: false
      - type: entities
        title: DTW Delays
        entities:
          - sensor.dtw_delay
          - sensor.dtw_ground_delay
          - sensor.dtw_ground_stop
          - sensor.dtw_end_time
          - input_boolean.dtw_notify
        show_header_toggle: false
      - type: entities
        title: LGA Delays
        entities:
          - sensor.lga_delay
          - sensor.lga_ground_delay
          - sensor.lga_ground_stop
          - sensor.lga_end_time
          - input_boolean.lga_notify
        show_header_toggle: false
      - type: entities
        title: JFK Delays
        entities:
          - sensor.jfk_delay
          - sensor.jfk_ground_delay
          - sensor.jfk_ground_stop
          - sensor.jfk_end_time
          - input_boolean.jfk_notify
        show_header_toggle: false
      - type: entities
        title: BOS Delays
        entities:
          - sensor.bos_delay
          - sensor.bos_ground_delay
          - sensor.bos_ground_stop
          - sensor.bos_end_time
          - input_boolean.bos_notify
        show_header_toggle: false
      - type: entities
        title: ORD Delays
        entities:
          - sensor.ord_delay
          - sensor.ord_ground_delay
          - sensor.ord_ground_stop
          - sensor.ord_end_time
          - input_boolean.ord_notify
        show_header_toggle: false

  - path: config
    title: config
    icon: mdi:settings
    cards:
      - type: entity-filter
        entities:
          - group.loopable_scripts
        state_filter:
          - "on"
        card:
          type: entity-button
          tap_action:
            action: call-service
            service: script.script_loop_stop
          entity: script.script_loop_stop
          name: Stop Loop
        show_empty: false
      - type: entities
        title: Status
        entities:
          - input_boolean.trip_mode
          - input_boolean.sleep_mode
          - group.all_lights
      - type: entities
        title: Alarm Clock
        entities:
          - input_boolean.alarm_clock_enable
          - input_datetime.alarm_clock
          - input_boolean.alarm_clock_coffee
      - type: entities
        title: Notification Automations
        entities:
          - automation.front_door
          - automation.climate_notifications
          - automation.atl_ground_delay
          - automation.atl_ground_stop
          - automation.atl_gs_cancel
          - automation.dtw_ground_delay
          - automation.dtw_ground_stop
          - automation.dtw_gs_cancel
          - automation.lga_ground_delay
          - automation.lga_ground_stop
          - automation.lga_gs_cancel
          - automation.jfk_ground_delay
          - automation.jfk_ground_stop
          - automation.jfk_gs_cancel
          - automation.bos_ground_delay
          - automation.bos_ground_stop
          - automation.bos_gs_cancel
          - automation.ord_ground_delay
          - automation.ord_ground_stop
          - automation.ord_gs_cancel
      - type: entities
        title: Light Automations
        entities:
          - automation.away_lights
          - automation.home_lights
      - type: entities
        title: Climate Automations
        entities:
          - automation.climate_set_cool
          - automation.climate_set_heat
          - automation.climate_set_home
          - automation.climate_set_away
          - automation.climate_set_trip
      - type: entities
        title: Other Automations
        entities:
          - automation.toggle_trip_mode
      - type: entities
        entities:
          - script.adam_mp3
