---

title: Home
views:

  - path: default_view
    title: Home
    cards:
#      - type: conditional
#        conditions:
#          - entity: sensor.fulton_county
#            state_not: '0'
#        card:
#          type: markdown
#          content: >
#            ## Active Weather Alerts:
#
#            {% for alert in state_attr("sensor.fulton_county", "alerts") %}
#              {{ alert.event }}
#            {%- endfor %}
      - type: glance
        entities:
#          - binary_sensor.weather_alert
          - binary_sensor.front_door
          - person.nathan
          - person.sara
          - sensor.indoor_temperature
          - sensor.nws_temperature
#          - sensor.outdoor_temperature
#          - sensor.cabinet_temperature
      - type: custom:stack-in-card
        title: Lights and Switches
        cards:
          - type: button
            entity: light.all
            name: All Lights Off
            tap_action:
              action: call-service
              service: light.turn_off
              service_data:
                entity_id: light.all
          - type: entities
            entities:
              - type: divider
          - type: horizontal-stack
            cards:
              - type: button
                entity: light.kitchen_lights
                name: Kitchen
              - type: button
                entity: switch.living_room_fan
                name: Fan
          - type: entities
            entities:
              - type: divider
          - type: custom:light-brightness-preset-row
            entity: light.island_dimmer
            name: Island
            customSetpoints: true
            LowBrightness: 20
            MedBrightness: 80
            HiBrightness: 255
          - type: custom:light-brightness-preset-row
            entity: light.living_room_lamp
            name: Lamp
            customSetpoints: true
            LowBrightness: 50
            MedBrightness: 128
            HiBrightness: 255
          - type: custom:light-brightness-preset-row
            entity: light.couch
            name: Couch
            customSetpoints: true
            LowBrightness: 50
            MedBrightness: 128
            HiBrightness: 255
          - type: entities
            entities:
              - type: divider
          - type: horizontal-stack
            cards:
              - type: button
                entity: light.balcony_lights
                name: Balcony
              - type: button
                entity: light.closet_light
                name: Closet
          - type: horizontal-stack
            cards:
              - type: button
                entity: switch.coffee_maker
                name: Coffee
              - type: button
                entity: switch.air_purifier
                name: Air Purifier
          - type: horizontal-stack
            cards:
              - type: button
                entity: light.hallway_light
                name: Hallway
              - type: button
                entity: light.bedroom_light
                name: Bedroom
          - type: entities
            entities:
              - type: divider
          - type: custom:light-brightness-preset-row
            entity: light.bedroom_lamp
            name: Bed Lamp
            customSetpoints: true
            LowBrightness: 50
            MedBrightness: 128
            HiBrightness: 255
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.travel_home_to_atl
                graph: line
                detail: 1
                name: To ATL
              - type: sensor
                entity: sensor.travel_atl_to_home
                graph: line
                detail: 1
                name: From ATL
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.travel_home_to_gdot
                graph: line
                detail: 1
                name: To GDOT
              - type: sensor
                entity: sensor.travel_gdot_to_home
                graph: line
                detail: 1
                name: From GDOT
      - type: gauge
        entity: sensor.allergy_index_today
        min: 0.0
        max: 12.0
        severity:
          green: 0
          yellow: 4.8
          red: 7.3
        name: Pollen Today
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: script.house_cold
            icon: mdi:snowflake
            tap_action:
              action: call-service
              service: script.house_cold
          - type: entity-button
            entity: script.house_hot
            icon: mdi:fire
            tap_action:
              action: call-service
              service: script.house_hot
      - type: history-graph
        entities:
          - sensor.indoor_temperature
          - sensor.nws_temperature
        title: Status
      - type: weather-forecast
        entity: weather.katl_hourly

  - path: vacuum
    title: Vacuum
    icon: mdi:robot-vacuum
    cards:
      - type: 'custom:vacuum-card'
        entity: vacuum.rockrobo
        map: camera.rockrobo_map
        stats:
          default:
            - attribute: mainBrush
              unit: h
              subtitle: Brush
            - attribute: sideBrush
              unit: h
              subtitle: Side
            - attribute: filter
              unit: h
              subtitle: Filter
            - attribute: sensor
              unit: h
              subtitle: Sensor
          cleaning:
            - attribute: cleanTime
              unit: h
              subtitle: Time
            - attribute: cleanArea
              unit: m2
              subtitle: Area
        actions:
          - name: Clean Bedroom
            icon: mdi:bed
            service: vacuum.send_command
            service_data:
              entity_id: vacuum.rockrobo
              command: zoned_cleanup
              params:
                'zone_ids': ['Bedroom']
          - name: Clean Bathroom
            icon: mdi:shower
            service: vacuum.send_command
            service_data:
              entity_id: vacuum.rockrobo
              command: zoned_cleanup
              params:
                'zone_ids': ['Bathroom']
          - name: Clean Kitchen
            icon: mdi:stove
            service: vacuum.send_command
            service_data:
              entity_id: vacuum.rockrobo
              command: zoned_cleanup
              params:
                'zone_ids': ['Kitchen']
          - name: Clean Litter Box
            icon: mdi:cat
            service: vacuum.send_command
            service_data:
              entity_id: vacuum.rockrobo
              command: zoned_cleanup
              params:
                'zone_ids': ['Litter Box']

  - path: alarm_clock
    title: Alarm Clock
    icon: mdi:alarm
    cards:
      - type: entities
        entities:
          - input_boolean.alarm_clock_enable
          - input_datetime.alarm_clock
        title: Alarm Clock
        show_header_toggle: false
      - type: entities
        entities:
          - input_boolean.alarm_clock_coffee
          - input_boolean.alarm_clock_lights
        show_header_toggle: false

  - path: living_room
    title: Living Room
    badges:
      - binary_sensor.front_door
      - sensor.living_room_fan_power
      - sensor.living_room_fan_energy
      - sensor.kitchen_light_switch_power
      - sensor.kitchen_light_switch_energy
      - sensor.balcony_christmas_light_plug_power
      - sensor.balcony_christmas_light_plug_energy
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Kitchen Sensor
            entities:
              - sensor.kitchen_temperature_z
              - sensor.kitchen_humidity_z
              - sensor.kitchen_illuminance_z
              - binary_sensor.kitchen_motion_z
            show_name: false
          - type: entity-button
            entity: light.hallway_light
            name: Hallway
      - type: vertical-stack
        cards:
          - type: glance
            title: Hallway Sensor
            entities:
              - sensor.hallway_temperature_z
              - sensor.hallway_humidity_z
              - sensor.hallway_illuminance_z
              - binary_sensor.hallway_motion_z
            show_name: false
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: light.kitchen_lights
                name: Kitchen
              - type: entity-button
                entity: switch.coffee_maker
                name: Coffee
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.island_dimmer
                name: Island
              - type: entity-button
                entity: switch.living_room_fan
                name: Fan
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.living_room_lamp
                name: Lamp
              - type: light
                entity: light.couch
                name: Couch

  - path: bedroom
    title: Bedroom
    badges:
      - binary_sensor.bedroom_window_1
      - binary_sensor.bedroom_window_2
      - binary_sensor.bedroom_window_3
      - sensor.desk_plug_power
      - sensor.desk_plug_energy
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Bedroom Sensor (Z)
            entities:
              - sensor.bedroom_temperature_z
              - sensor.bedroom_humidity_z
              - sensor.bedroom_illuminance_z
              - binary_sensor.bedroom_motion_z
            show_name: false
          - type: glance
            title: Bedroom Sensor
            entities:
              - sensor.bedroom_temperature
              - sensor.bedroom_humidity
            show_name: false
      - type: entities
        entities:
          - light.bedroom_light
          - light.bedroom_lamp
          - light.bedroom_led
          - light.closet_light
          - switch.desk_plug

  - path: bathroom
    title: Bathroom
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Bathroom Sensor (Z)
            entities:
              - sensor.bathroom_temperature_z
              - sensor.bathroom_humidity_z
              - sensor.bathroom_illuminance_z
              - binary_sensor.bathroom_motion_z
            show_name: false
          - type: glance
            title: Bathroom Sensor
            entities:
              - sensor.bathroom_temperature
              - sensor.bathroom_humidity
              - sensor.bathroom_luminance
              - binary_sensor.bathroom_motion
            show_name: false
      - type: entity-button
        entity: light.bathroom_lights

  - path: climate
    title: Climate
    icon: mdi:air-conditioner
    badges:
      - sensor.thermostat_temperature
      - sensor.thermostat_humidity
      - sensor.hvac_action
      - sensor.ac_cool_today
      - sensor.ac_heat_today
    cards:
      - type: thermostat
        entity: climate.thermostat
      - type: entities
        entities:
          - input_boolean.climate_override
          - input_number.climate_heat_point
          - input_number.climate_cool_point
          - input_number.climate_heat_default
          - input_number.climate_cool_default
          - input_number.climate_away_offset
          - input_number.climate_trip_offset
          - input_number.climate_sleep_offset

  - path: media-player
    title: Media Player
    icon: mdi:music
    cards:
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.apple_tv
          - type: horizontal-stack
            cards:
              - type: button
                name: Turn On
                icon: mdi:power-standby
                tap_action:
                  action: call-service
                  service: script.apple_tv_on
              - type: button
                name: Turn Off
                icon: mdi:power-off
                tap_action:
                  action: call-service
                  service: script.apple_tv_off
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: button
                name: Up
                icon: mdi:arrow-up
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:
                    entity_id: remote.apple_tv
                    command: 'up'
              - type: vertical-stack
                cards:
                  - type: button
                    name: Left
                    icon: mdi:arrow-left
                    tap_action:
                      action: call-service
                      service: remote.send_command
                      service_data:
                        entity_id: remote.apple_tv
                        command: 'left'
                  - type: button
                    name: Right
                    icon: mdi:arrow-right
                    tap_action:
                      action: call-service
                      service: remote.send_command
                      service_data:
                        entity_id: remote.apple_tv
                        command: 'right'
              - type: button
                name: Down
                icon: mdi:arrow-down
                tap_action:
                  action: call-service
                  service: remote.send_command
                  service_data:
                    entity_id: remote.apple_tv
                    command: 'down'

  - path: delays
    title: Delays
    icon: mdi:airplane
    badges:
      - sensor.next_report_time
      - sensor.time_to_leave
    cards:
      - type: entities
        title: ATL Status
        show_header_toggle: false
        entities:
          - binary_sensor.atl_departure_delay
          - binary_sensor.atl_arrival_delay
          - binary_sensor.atl_ground_delay
          - binary_sensor.atl_ground_stop
          - binary_sensor.atl_closure
      - type: entities
        title: DTW Status
        show_header_toggle: false
        entities:
          - binary_sensor.dtw_departure_delay
          - binary_sensor.dtw_arrival_delay
          - binary_sensor.dtw_ground_delay
          - binary_sensor.dtw_ground_stop
          - binary_sensor.dtw_closure
      - type: entities
        title: LGA Status
        show_header_toggle: false
        entities:
          - binary_sensor.lga_departure_delay
          - binary_sensor.lga_arrival_delay
          - binary_sensor.lga_ground_delay
          - binary_sensor.lga_ground_stop
          - binary_sensor.lga_closure
      - type: entities
        title: JFK Status
        show_header_toggle: false
        entities:
          - binary_sensor.jfk_departure_delay
          - binary_sensor.jfk_arrival_delay
          - binary_sensor.jfk_ground_delay
          - binary_sensor.jfk_ground_stop
          - binary_sensor.jfk_closure
      - type: entities
        title: BOS Status
        show_header_toggle: false
        entities:
          - binary_sensor.bos_departure_delay
          - binary_sensor.bos_arrival_delay
          - binary_sensor.bos_ground_delay
          - binary_sensor.bos_ground_stop
          - binary_sensor.bos_closure
      - type: entities
        title: ORD Status
        show_header_toggle: false
        entities:
          - binary_sensor.ord_departure_delay
          - binary_sensor.ord_arrival_delay
          - binary_sensor.ord_ground_delay
          - binary_sensor.ord_ground_stop
          - binary_sensor.ord_closure

  - path: config
    title: config
    icon: mdi:cog
    cards:
      - type: entities
        title: Status
        show_header_toggle: false
        entities:
          - input_boolean.trip_mode
          - input_boolean.sleep_mode
          - group.outdoor_doors_windows
          - input_boolean.dumb_mode
          - light.all
          - group.home_devices
          - binary_sensor.updater
          - sensor.hacs
      - type: entities
        title: Pi-Hole
        entities:
          - sensor.pi_hole_ads_blocked_today
          - sensor.pi_hole_ads_percentage_blocked_today
          - sensor.pi_hole_dns_queries_cached
          - sensor.pi_hole_dns_queries_forwarded
          - sensor.pi_hole_dns_queries_today
          - sensor.pi_hole_dns_unique_clients
          - sensor.pi_hole_dns_unique_domains
          - sensor.pi_hole_domains_blocked
          - sensor.pi_hole_seen_clients
      - type: horizontal-stack
        cards:
          - type: button
            name: Pi-Hole Disable
            icon: mdi:cloud-off-outline
            tap_action:
              action: call-service
              service: pi_hole.disable
              service_data:
                duration: 00:00:30
            double_tap_action:
              action: call-service
              service: pi_hole.disable
              service_data:
                duration: 00:05:00
          - type: button
            name: Pi-Hole Enable
            icon: mdi:cloud-outline
            tap_action:
              action: call-service
              service: switch.turn_on
              service_data:
                entity_id: switch.pi_hole


      - type: entities
        title: Scenes
        entities:
          - scene.night_lights
          - scene.normal_lights
          - scene.tv_lights
      - type: gauge
        name: CPU Usage
        entity: sensor.processor_use
      - type: gauge
        name: Memory Usage
        entity: sensor.memory_use_percent
      - type: gauge
        name: Disk Usage
        entity: sensor.disk_use_percent
      - type: sensor
        name: CPU Temp
        entity: sensor.processor_temperature
