---
# This automation turns off all lights as well as the coffee maker, fan, and
# sleep mode when we leave home.

- alias: Away Lights
  id: "away_lights"
  trigger:
    platform: state
    entity_id: group.home_devices
    to: "not_home"
  condition:
    condition: state
    entity_id: input_boolean.dumb_mode
    state: "off"
  action:
    - service: light.turn_off
      data:
        entity_id: light.all
    - service: homeassistant.turn_off
      data:
        entity_id: switch.coffee_maker
    - service: input_boolean.turn_off
      entity_id: input_boolean.sleep_mode
    - service: switch.turn_off
      entity_id: switch.living_room_fan
    - condition: state
      entity_id: input_boolean.holiday_mode
      state: "on"
    - service: switch.turn_off
      entity_id: switch.christmas_tree
