---
# Simple automations to control the lights in the closet. Opening the door
# or turning on the switch will turn them off, they will turn off only if
# both the switch is off for 15 seconds and the door is closed.

- alias: Closet Lights On
  id: "closet_lights_on"
  trigger:
    - platform: state
      entity_id: binary_sensor.closet_door
      to: "on"
    - platform: state
      entity_id: binary_sensor.closet_light_switch_input
      to: "on"
  action:
    service: light.turn_on
    entity_id: light.closet_light

- alias: Closet Lights Off
  id: "closet_lights_off"
  trigger:
    - platform: state
      entity_id: binary_sensor.closet_door
      to: "off"
    - platform: state
      entity_id: binary_sensor.closet_light_switch_input
      to: "off"
      for:
        seconds: 15
  condition:
    condition: state
    entity_id: binary_sensor.closet_light_switch_input
    state: "off"
  action:
    service: light.turn_off
    entity_id: light.closet_light
