---
# This automation turns on the hallway lights if there is motion and it is dark.

- alias: Hallway Motion Lights On
  id: "hallway_motion_lights_on"
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_z
      to: "on"
  condition:
    - condition: state
      entity_id: group.home_devices
      state: "home"
    - condition: numeric_state
      entity_id: sensor.hallway_illuminance_z
      below: 50
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.hallway_light

- alias: Hallway Lights Off
  id: "hallway_lights_off"
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_z
      to: "off"
      for:
        minutes: 3
  action:
    - service: light.turn_off
      entity_id: light.hallway_light
