---
# This automation triggers the kitchen lights based on motion. It also turns them off after a period of no motion.
# This is still a work in progress.

- alias: Kitchen Lights On
  id: "kitchen_lights_on"
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_z
    to: "on"
  condition:
    - condition: state
      entity_id: group.home_devices
      state: "home"
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: "off"
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.kitchen_lights

- alias: Kitchen Lights Off
  id: "kitchen_lights_off"
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_z
    to: "off"
    for:
      minutes: 3
  condition:
    condition: state
    entity_id: input_boolean.dumb_mode
    state: "off"
  action:
    service: light.turn_off
    entity_id: light.kitchen_lights

- alias: Kitchen Cabinet Lights
  id: "kitchen_cabinet_lights"
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_z
      to: "on"
    - platform: state
      entity_id: binary_sensor.living_room_motion_z
      to: "on"
  condition:
    - condition: state
      entity_id: group.home_devices
      state: "home"
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: "off"
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.wled_kitchen_master
