---
# These automations manage our night lights.

- alias: Night Lights
  id: "night_lights"
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_motion_z
    to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: "on"
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.night_lights

- alias: Night Lights Off
  id: "night_lights_off"
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_z
    to: "off"
    for:
      minutes: 3
  condition:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: "on"
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: "off"
  action:
    - service: light.turn_off
      entity_id: light.island_dimmer
    - service: light.turn_off
      entity_id: light.wled_kitchen_master

- alias: Night Lights Off in Morning
  id: "night_lights_off_in_morning"
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:15:00"
  condition:
    - condition: template
      value_template: "{{ state_attr('light.island_dimmer', 'brightness') < 30 }}"
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: "off"
  action:
    - service: light.turn_off
      entity_id: light.island_dimmer
    - service: script.led_on
