---

# This automation turns the lights back off after Sara leaves home for work
# if motion has not been detected in the living room since she left (ie. Nathan
# is still in bed).

- alias: Sara to Work
  trigger:
    platform: state
    entity_id: person.sara
    to: 'not_home'
  condition:
    - condition: state
      entity_id: binary_sensor.living_room_motion_z
      state: 'off'
      for:
        minutes: 3
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: time
      after: '04:00:00'
      before: '08:00:00'
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: 'off'
  action:
    service: light.turn_off
    entity_id: light.all
