---

# This automation is to control the Wemo smart plug that runs our air purifier.

# Air purifier has the following priority:
# 1. Should always run when the HVAC is running
# 2. Should always be on while windows are open
# 3. Should turn off when TV is playing
# 4. Should otherwise be on while we are home
# 5. While we are gone, should revert to a cycle depending on pollen count

# Additionally, the automations will wait until it has been at least 30 seconds
# from the last state change to not cycle it frequently.

- alias: Air Purifier On During AC
  trigger:
    platform: state
    entity_id: climate.thermostat
    attribute: hvac_action
    from: "idle"
  condition:
    condition: state
    entity_id: input_boolean.dumb_mode
    state: 'off'
  action:
    - wait_template: "{{ as_timestamp(states.sensor.date_time_iso.state) - as_timestamp(states.switch.air_purifier.last_changed) > 30}}"
    - service: switch.turn_on
      entity_id: switch.air_purifier
- alias: Air Purifier On Windows Open
  trigger:
    platform: state
    entity_id: group.outdoor_doors_windows
    to: 'on'
    for:
      seconds: 15
  action:
    - wait_template: "{{ as_timestamp(states.sensor.date_time_iso.state) - as_timestamp(states.switch.air_purifier.last_changed) > 30}}"
    - service: switch.turn_on
      entity_id: switch.air_purifier

- alias: Air Purifier Off During TV
  trigger:
    platform: state
    entity_id: media_player.apple_tv
    to: 'playing'
  condition:
    - condition: state
      entity_id: climate.thermostat
      attribute: 'hvac_action'
      state: 'idle'
    - condition: state
      entity_id: group.outdoor_doors_windows
      state: 'off'
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: 'off'
  action:
    - wait_template: "{{ as_timestamp(states.sensor.date_time_iso.state) - as_timestamp(states.switch.air_purifier.last_changed) > 30}}"
    - service: switch.turn_off
      entity_id: switch.air_purifier

- alias: Air Purifier Off During TV After HVAC or Windows
  trigger:
    - platform: state
      entity_id: climate.thermostat
      attribute: 'hvac_action'
      to: 'idle'
    - platform: state
      entity_id: group.outdoor_doors_windows
      to: 'off'
  condition:
    - condition: state
      entity_id: media_player.apple_tv
      state: 'playing'
    - condition: state
      entity_id: group.outdoor_doors_windows
      state: 'off'
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: 'off'
  action:
    - wait_template: "{{ as_timestamp(states.sensor.date_time_iso.state) - as_timestamp(states.switch.air_purifier.last_changed) > 30}}"
    - service: switch.turn_off
      entity_id: switch.air_purifier

- alias: Air Purifier On When Home
  trigger:
    - platform: state
      entity_id: group.home_devices
      to: 'home'
    - platform: state
      entity_id: media_player.apple_tv
    - platform: state
      entity_id: binary_sensor.smoke_detector_smoke_detected
      to: 'off'
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.apple_tv
          state: "playing"
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: 'off'
  action:
    - wait_template: "{{ as_timestamp(states.sensor.date_time_iso.state) - as_timestamp(states.switch.air_purifier.last_changed) > 30}}"
    - service: switch.turn_on
      entity_id: switch.air_purifier

- alias: Air Purifier Cycle High
  trigger:
    platform: time_pattern
    hours: '/1'
  condition:
    condition: numeric_state
    entity_id: sensor.allergy_index_today
    above: 7
  action:
    service: input_boolean.toggle
    entity_id: input_boolean.air_purifier_cycle

- alias: Air Purifier Cycle Low
  trigger:
    platform: time_pattern
    hours: '/4'
  condition:
    condition: numeric_state
    entity_id: sensor.allergy_index_today
    below: 7
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.air_purifier_cycle
    - delay: '01:00:00'
    - service: input_boolean.turn_off
      entity_id: input_boolean.air_purifier_cycle

- alias: Air Purifier Set Not Home
  trigger:
    - platform: state
      entity_id: group.home_devices
      to: 'not_home'
    - platform: state
      entity_id: climate.thermostat
      attribute: 'hvac_action'
    - platform: state
      entity_id: input_boolean.air_purifier_cycle
  condition:
    - condition: state
      entity_id: group.home_devices
      state: 'not_home'
    - condition: state
      entity_id: climate.thermostat
      attribute: 'hvac_action'
      state: 'idle'
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: 'off'
  action:
    service: >
      {% if states('input_boolean.air_purifier_cycle') == 'on' %}
      switch.turn_on
      {% else %}
      switch.turn_off
      {% endif %}
    entity_id: switch.air_purifier
