---

# This automation turns the climate on or off when the windows are opened or
# closed.

- alias: Climate Turn Off
  trigger:
    platform: state
    entity_id: group.outdoor_doors_windows
    to: 'on'
    for:
      seconds: 30
  condition:
    condition: state
    entity_id: input_boolean.dumb_mode
    state: 'off'
  action:
    service: climate.turn_off
    entity_id: climate.thermostat_77_05_2a

- alias: Climate Turn On
  trigger:
    - platform: state
      entity_id: group.outdoor_doors_windows
      to: 'off'
      for:
        seconds: 30
    - platform: state
      entity_id: binary_sensor.smoke_detector_smoke_detected
      to: 'off'
  condition:
    - condition: state
      entity_id: group.outdoor_doors_windows
      state: 'off'
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: 'off'
  action:
    service: climate.turn_on
    data:
      entity_id: climate.thermostat_77_05_2a

- alias: Climate Set Mode
  trigger:
    - platform: template
      value_template: "{{ states('sensor.thermostat_temperature') > states('input_number.climate_cool_point') }}"
    - platform: template
      value_template: "{{ states('sensor.thermostat_temperature') < states('input_number.climate_heat_point') }}"
    - platform: state
      entity_id: climate.thermostat_77_05_2a
      from: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: 'off'
    - condition: not
      conditions:
        - condition: state
          entity_id: climate.thermostat_77_05_2a
          state: 'off'
  action:
    - service: climate.set_hvac_mode
      entity_id: climate.thermostat_77_05_2a
      data_template:
        hvac_mode: >
          {% if states('sensor.thermostat_temperature') < states('input_number.climate_heat_point') %}
            heat
          {% else %}
            cool
          {% endif %}
