---
# This automation turns the climate on or off when the windows are opened or
# closed.

- alias: Climate Turn Off
  id: "climate_turn_off"
  trigger:
    platform: state
    entity_id: group.outdoor_doors_windows
    to: "on"
    for:
      seconds: 30
  condition:
    condition: state
    entity_id: input_boolean.dumb_mode
    state: "off"
  action:
    service: climate.turn_off
    entity_id: climate.thermostat

- alias: Climate Turn On
  id: "climate_turn_on"
  trigger:
    - platform: state
      entity_id: group.outdoor_doors_windows
      to: "off"
      for:
        seconds: 30
    - platform: state
      entity_id: binary_sensor.smoke_detector_smoke_detected
      to: "off"
  condition:
    - condition: state
      entity_id: group.outdoor_doors_windows
      state: "off"
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: "off"
  action:
    service: climate.turn_on
    data:
      entity_id: climate.thermostat
