- alias: Record AC Cool Time
  trigger:
    platform: time
    at: "23:59:45"
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.previous_day_ac_cool
      value: "{{ states('sensor.ac_cool_today') }}"
# This is currently unused but would like to get it working in the future
#- alias: Record Average
#  trigger:
#    platform: time
#    at: "23:59:45"
#  action:
#    service: input_number.set_value
#    data_template:
#      entity_id: input_number.previous_day_average_temp
#      value: "{{ states('sensor.outdoor_temperature_stats_mean')}}"
