---
# This serves as a workaround to the Z-Wave thermostat not updating values.
# It updates all three values with delays in between to not overload the
# Z-Wave network.

- alias: Update Thermostat Values
  id: "update_thermostat_values"
  trigger:
    - platform: time_pattern
      minutes: "/5"
  action:
    - service: zwave_js.refresh_value
      data:
        entity_id: sensor.thermostat_temperature
    - alias: "delay_30s"
      delay: 30
    - service: zwave_js.refresh_value
      data:
        entity_id: sensor.thermostat_humidity
    - alias: "delay_30s"
      delay: 30
    - service: zwave_js.refresh_value
      data:
        entity_id: climate.thermostat
