---

# This automation sets the setpoint on the thermostat when the climate setpoint
# input numbers change. It also runs any time the thermostat is turned on in
# case the setpoint has changed since it was turned off (ie. change to sleep
# mode before windows are closed)

- alias: Climate Set Point
  mode: restart
  trigger:
    - platform: state
      entity_id: input_number.climate_cool_point
    - platform: state
      entity_id: input_number.climate_heat_point
    - platform: state
      entity_id: input_boolean.climate_override
      to: 'off'
    - platform: state
      entity_id: climate.thermostat_77_05_2a
      to: 'heat'
    - platform: state
      entity_id: climate.thermostat_77_05_2a
      to: 'cool'
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: climate.thermostat_77_05_2a
          state: 'off'
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: 'off'
  action:
    - delay: '00:00:05'
    - choose:
      - conditions: # yamllint disable-line rule:indentation
        - condition: state # yamllint disable-line rule:indentation
          entity_id: climate.thermostat_77_05_2a
          state: 'heat'
        sequence:
          - service: climate.set_temperature
            data:
              entity_id: climate.thermostat_77_05_2a
              temperature: '{{ states("input_number.climate_heat_point") }}'
      - conditions:
        - condition: state # yamllint disable-line rule:indentation
          entity_id: climate.thermostat_77_05_2a
          state: 'cool'
        sequence:
          - service: climate.set_temperature
            data:
              entity_id: climate.thermostat_77_05_2a
              temperature: '{{ states("input_number.climate_cool_point") }}'
