---

# These automations turn sleep mode on and off based on our usual routines.

- alias: Turn Sleep Mode Off
  trigger:
    - platform: state
      entity_id: switch.coffee_maker
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_door
    - platform: sun
      event: sunrise
      offset: '+00:15:00'
  condition:
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: 'off'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.sleep_mode

- alias: Turn Sleep Mode On
  trigger:
    platform: state
    entity_id: light.all
    to: 'off'
  condition:
    - condition: time
      after: '21:00:00'
      before: '03:00:00'
    - condition: state
      entity_id: group.home_devices
      state: 'home'
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.sleep_mode
    - service: switch.turn_off
      entity_id: switch.living_room_fan
