---

esphome:
  name: airgradient
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "52e97c0387d79994775a73acc2756949"

wifi:
  ssid: !secret ssid
  password: !secret wifipw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Airgradient Fallback Hotspot"
    password: "aSWXtYw0vW5v"

captive_portal:

i2c:
  sda: D2
  scl: D1

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart1
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart2

sensor:
  - platform: sht3xd
    temperature:
      id: temp
      name: "Bedroom Temperature"
    humidity:
      id: humidity
      name: "Bedroom Humidity"
    address: 0x44
    update_interval: 5s
  - platform: pmsx003
    type: PMSX003
    uart_id: uart1
    pm_2_5:
      id: pm25
      name: "Bedroom Particulate Matter <2.5µm Concentration"
  - platform: senseair
    uart_id: uart2
    co2:
      id: co2
      name: "Bedroom SenseAir CO2 Value"
    update_interval: 60s

font:
  - file: "fonts/OpenSans.ttf"
    id: opensans
    size: 12
    glyphs: |
      !"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzµ³/

display:
  - platform: ssd1306_i2c
    model: "SSD1306 64x48"
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(opensans), "%.1f°F", (id(temp).state * 1.8) + 32);
      it.printf(0, 12, id(opensans), "%.1f%% RH", id(humidity).state);
      it.printf(0, 24, id(opensans), "%.0fppm", id(co2).state);
      it.printf(0, 36, id(opensans), "%.0f µg/m³", id(pm25).state);
